name = "Moconinja's theme"
license = "GPLv2"
licenselink = "https://github.com/MocoNinja/moconinjas_theme/blob/master/LICENSE"
description = "A custom theme to both learn HUGO and try to create a pointless online site..."
tags = []
features = []
min_version = "0.41.0"
languageCode = 'es-es'
[author]
	name = "MocoNinja"
